# Project Information
site_name: OI Wiki
site_description: OI Wiki 是一个编程竞赛知识整合站点，提供有趣又实用的编程竞赛知识以及其他有帮助的内容，帮助广大编程竞赛爱好者更快更深入地学习编程竞赛
site_author: OI Wiki Team
site_url: https://oi-wiki.org
strict: false

# Repository
repo_name: 'OI-wiki/OI-wiki'
repo_url: 'https://github.com/OI-wiki/OI-wiki'
edit_uri: 'https://oi-wiki.org/edit-landing/?ref='

# Copyright
copyright: 'Copyright &copy; 2016 - 2023 OI Wiki Team'

# Contents
nav:
  - 字符串:
    - 字符串哈希: string/hash.md
    - Boyer–Moore 算法: string/bm.md
    - Z 函数（扩展 KMP）: string/z-func.md
    - AC 自动机: string/ac-automaton.md
    - 后缀数组 (SA):
      - 后缀数组简介: string/sa.md
      - 最优原地后缀排序算法: string/sa-optimal-inplace.md
    - 后缀自动机 (SAM): string/sam.md
    - Manacher: string/manacher.md
    - 回文树: string/pam.md
    - 最小表示法: string/minimal-string.md
    - Lyndon 分解: string/lyndon.md
  - 数学:
    - 位运算: math/bit.md
    - 二进制集合操作: math/binary-set.md
    - 数论:
      - 最大公约数: math/number-theory/gcd.md
      - 数论分块: math/number-theory/sqrt-decomposition.md
      - 欧拉函数: math/number-theory/euler-totient.md
      - 分解质因数: math/number-theory/pollard-rho.md
      - 裴蜀定理: math/number-theory/bezouts.md
      - 类欧几里德算法: math/number-theory/euclidean.md
      - 欧拉定理 & 费马小定理: math/number-theory/fermat.md
      - 线性同余方程: math/number-theory/linear-equation.md
      - 中国剩余定理: math/number-theory/crt.md
      - 升幂引理: math/number-theory/lift-the-exponent.md
      - 威尔逊定理: math/number-theory/wilson.md
      - 卢卡斯定理: math/number-theory/lucas.md
      - 同余方程: math/number-theory/congruence-equation.md
      - 二次剩余: math/number-theory/quad-residue.md
      - 原根: math/number-theory/primitive-root.md
      - 离散对数: math/number-theory/discrete-logarithm.md
      - 剩余: math/number-theory/residue.md
      - 莫比乌斯反演: math/number-theory/mobius.md
      - 杜教筛: math/number-theory/du.md
      - Powerful Number 筛: math/number-theory/powerful-number.md
      - Stern–Brocot 树与 Farey 序列: math/number-theory/stern-brocot.md
      - 二次域: math/number-theory/quadratic.md
      - 循环连分数: math/number-theory/periodic-continued-fraction.md
      - Pell 方程: math/number-theory/pell-equation.md
    - 多项式与生成函数:
      - 快速数论变换: math/poly/ntt.md
      - 快速沃尔什变换: math/poly/fwt.md
      - 多项式初等函数: math/poly/elementary-func.md
      - 多项式平移|连续点值平移: math/poly/shift.md
    - 组合数学:
      - 容斥原理: math/combinatorics/inclusion-exclusion-principle.md
      - 康托展开: math/combinatorics/cantor.md
      - 斐波那契数列: math/combinatorics/fibonacci.md
      - 斯特林数: math/combinatorics/stirling.md
      - 贝尔数: math/combinatorics/bell.md
      - 伯努利数: math/combinatorics/bernoulli.md
      - Eulerian Number: math/combinatorics/eulerian.md
      - 分拆数: math/combinatorics/partition.md
      - 范德蒙德卷积: math/combinatorics/vandermonde-convolution.md
      - 图论计数: math/combinatorics/graph-enumeration.md
    - 线性代数:
      - 特征多项式: math/linear-algebra/char-poly.md
      - 对角化: math/linear-algebra/diagonalization.md
      - Jordan标准型: math/linear-algebra/jordan.md
    - 线性规划:
      - 线性规划简介: math/linear-programming.md
      - 单纯形算法: math/simplex.md
    - 博弈论: 
      - 博弈论简介: math/game-theory/intro.md
      - 公平组合游戏: math/game-theory/impartial-game.md
      - 非公平组合游戏: math/game-theory/partizan-game.md
      - 反常游戏: math/game-theory/misere-game.md
    - 数值算法:
      - 拉格朗日插值: math/numerical/lagrange.md
      - 数值积分: math/numerical/integral.md
      - 高斯消元: math/numerical/gauss.md
      - 牛顿迭代法: math/numerical/newton.md
    - 杨氏矩阵: math/young-tableau.md
  - 数据结构:
    - 哈希表: ds/hash.md
    - 线段树: ds/seg.md
    - 李超线段树: ds/li-chao-tree.md
    - 区间最值操作 & 区间历史最值: ds/seg-beats.md
    - 划分树: ds/dividing.md
    - 二叉搜索树 & 平衡树:
      - 二叉搜索树 & 平衡树: ds/bst.md
      - Treap: ds/treap.md
      - Splay 树: ds/splay.md
      - 笛卡尔树: ds/cartesian-tree.md
    - K-D Tree: ds/kdt.md
    - 动态树:
      - Link Cut Tree: ds/lct.md
    - 析合树: ds/divide-combine.md
  - 图论:
    - 树上问题:
      - 最近公共祖先: graph/lca.md
      - 树的重心: graph/tree-centroid.md
      - 树链剖分: graph/hld.md
      - 树上启发式合并: graph/dsu-on-tree.md
      - 虚树: graph/virtual-tree.md
      - 树分治: graph/tree-divide.md
      - AHU 算法: graph/tree-ahu.md
      - 树上随机游走: graph/tree-random-walk.md
    - 矩阵树定理: graph/matrix-tree.md
    - 斯坦纳树: graph/steiner-tree.md
    - 最小树形图: graph/dmst.md
    - 最小直径生成树: graph/mdst.md
    - 最短路: graph/shortest-path.md
    - 差分约束: graph/diff-constraints.md
    - k 短路: graph/kth-path.md
    - 同余最短路: graph/mod-shortest-path.md
    - 连通性相关:
      - 双连通分量: graph/bcc.md
      - 圆方树: graph/block-forest.md
      - 点/边连通度: graph/connectivity.md
    - 2-SAT: graph/2-sat.md
    - 欧拉图: graph/euler.md
    - 二分图: graph/bi-graph.md
    - 最小环: graph/min-cycle.md
    - 平面图: graph/planar.md
    - 网络流:
      - 最大流: graph/flow/max-flow.md
      - 最小割: graph/flow/min-cut.md
      - 费用流: graph/flow/min-cost.md
      - 上下界网络流: graph/flow/bound.md
    - Stoer–Wagner 算法: graph/stoer-wagner.md
    - 图的匹配:
      - 二分图最大匹配: graph/graph-matching/bigraph-match.md
      - 二分图最大权匹配: graph/graph-matching/bigraph-weight-match.md
      - 一般图最大匹配: graph/graph-matching/general-match.md
      - 一般图最大权匹配: graph/graph-matching/general-weight-match.md
    - Prüfer 序列: graph/prufer.md
    - LGV 引理: graph/lgv.md
    - 弦图: graph/chord.md
    - 最大团搜索算法: graph/max-clique.md
    - 支配树: graph/dominator-tree.md
    - 图上随机游走: graph/graph-random-walk.md
  - 计算几何:
    - 计算几何部分简介: geometry/index.md
    - 二维计算几何基础: geometry/2d.md
    - 三维计算几何基础: geometry/3d.md
    - 距离: geometry/distance.md
    - 三角剖分: geometry/triangulation.md
    - 凸包: geometry/convex-hull.md
    - 扫描线: geometry/scanning.md
    - 旋转卡壳: geometry/rotating-calipers.md
    - 半平面交: geometry/half-plane.md
    - 平面最近点对: geometry/nearest-points.md
    - 随机增量法: geometry/random-incremental.md
    - 反演变换: geometry/inverse.md
    - 计算几何杂项: geometry/misc.md
  - 杂项:
    - 离线算法:
      - 莫队算法:
        - 带修改莫队: misc/modifiable-mo-algo.md
        - 莫队配合 bitset: misc/mo-algo-with-bitset.md
    - 随机化:
      - 随机化技巧: misc/rand-technique.md
      - 爬山算法: misc/hill-climbing.md
      - 模拟退火: misc/simulated-annealing.md
    - Kahan 求和: misc/kahan-summation.md

# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material/templates'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.instant
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

plugins: []

hooks:
  - hooks/on_env.py

# Customization
extra:
  disqus: 'OI-Wiki'
  copyright: '<a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh">CC BY-SA 4.0</a> 和 <a href="https://github.com/zTrix/sata-license">SATA</a>'
  pagetime: 'on'
  manifest: 'manifest.webmanifest'
  githash: ''
  analytics:
    provider: google
    property: UA-124485594-1

extra_javascript:
  - '_static/js/math-csr.js?math-csr'
  - 'assets/vendor/mathjax/es5/tex-mml-chtml.js?math-csr'

extra_css:
  - '_static/css/extra.css?v=14'

# Extensions
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
